---
version: 2
models:
- name: "sv_go_account_report"
  columns:
  - name: "ad_network_type"
    dataType:
      type: "String"
  - name: "date_day"
    dataType:
      type: "Date"
  - name: "TOTAL_CLICKS"
    dataType:
      type: "Bigint"
  - name: "TOTAL_IMPRESSIONS"
    dataType:
      type: "Bigint"
  - name: "TOTAL_SPEND"
    dataType:
      type: "Double"
  - name: "account_id"
    dataType:
      type: "Integer"
  - name: "pretty_spend"
    dataType:
      type: "String"
  - name: "updated_at"
    dataType:
      type: "Timestamp"
  - name: "currency_code"
    dataType:
      type: "String"
  - name: "device"
    dataType:
      type: "String"
  tests: []
